# 开发环境配置
# 数据源配置，请修改为你项目的实际配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/study2
    username: root
    password: banggood
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level: debug
